### ISSUE TITLE
Code Serial Communication between Raspberry Pi and Arduino

### ISSUE THREAD

**Issue by mattdailis** [HopkinsRobotics2014-2015/Firefighter#6]
baud rate: 9600
- Check Sensors
- Send Readings from Arduino to RPi
- Wait for Response
- process response

**Comment by mattdailis** [comment]
Successfully established a connection today! Goal: Ramp up the baud rate to 115200 baud, establish a handshake.

Interesting application of Processing to arduino: http://scruss.com/blog/2014/01/07/processing-2-1-oracle-java-raspberry-pi-serial-arduino-%e2%98%ba/ I don't think this would be the best way for us, because it makes sense (in my mind) to divide the work between two processors and to minimize the use of the serial connection, but we'll see.

**Comment by davtsno** [comment]
How was the connection completed? Did Raspbian manage to work in this specific case? Various online sources and my own experience show that Raspbian usually craps out with usb serial connection, and no one is really sure why. Pidora always works, according to random online articles. Was the device create /dev/ttyAMA0?

Also any specific reason to ramp up the baud rate?

And have you ever considered python instead of java :P

From: Matt
Sent: ‎Thursday‎, ‎January‎ ‎29‎, ‎2015 ‎10‎:‎18‎ ‎PM
To: HopkinsRobotics2014-2015/Firefighter

Successfully established a connection today! Goal: Ramp up the baud rate to 115200 baud, establish a handshake.

Interesting application of Processing to arduino: http://scruss.com/blog/2014/01/07/processing-2-1-oracle-java-raspberry-pi-serial-arduino-%e2%98%ba/ I don't think this would be the best way for us, because it makes sense (in my mind) to divide the work between two processors and to minimize the use of the serial connection, but we'll see.

**Comment by mattdailis** [comment]
The code for the java side of the connection is [here](https://github.com/HopkinsRobotics2014-2015/Firefighter/blob/master/Code-for-Raspberry-Pi/ArduinoSerialConnection.java)

Raspbian did work, so I think we'll stick to it unless we run into a dead end that forces us to switch.

The higher baud rate seemed to make the connection faster, although its possible that I had made a mistake in coding the original 9600 handshake which slowed it down. 

Python is a good idea, but because the majority of our programming team is familiar with Processing/Java we're going to stick with that.

Closing this issue to give us a sense of progress ;)
